language: java

before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - cd Backend
  - mvn test -B
  - mvn verify

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: dist